class UsblCommand:
    MOTION_COMPENSATED_TRACKING_POSITION_DATA = "AT?UPX"
    TRACKING_POSITION_DATA = "AT?UP"
    FIRMWARE_INFORMATION = "ATI"
    ACOUSTIC_CONNECTION_STATUS = "AT?S"
    SEND_INSTANT_MESSAGE_WITH_ACKNOLEDGEMENT = "AT*SENDIM"
    SEND_INSTANT_MESSAGE_WITHOUT_ACKNOLEDGEMENT = "AT*SENDIM"